/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2018 Red Hat, Inc., and individual contributors
 * as indicated by the @author tags.
 * <p>
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * <p>
 * http://www.apache.org/licenses/LICENSE-2.0
 * <p>
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.pnc.bacon.cli;

/**
 * @author Michal Szynkiewicz, michal.l.szynkiewicz@gmail.com
 * <br>
 * Date: 12/13/18
 *
 * == AUTOGENERATED == from src/main/templates/org/jboss/pnc/bacon/cli/Constants.java folder
 *
 * == <IMPORTANT> ======================================================================================================
 * == If you want to edit this file, please edit the file from the templates folder instead
 * ==
 * == If you want to move this file, don't forget to edit the pom.xml to point to the new location !!!
 * == </IMPORTANT> =====================================================================================================
 */
public class Constants {
    private Constants(){}

    public static final String VERSION = "@version.bacon@";
    public static final String COMMIT_ID_SHA = "@commit.id.abbrev@";
    public static final String NO_VALUE = "a default value isn't provided";
}
