name: Validate GitHub Actions Workflows for this shared actions repo
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@646d9b629925d6405fb06ed1476aefd6b2cdca86 # v0.0.23
