name: Validate GitHub Actions Workflows for this shared actions repo
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: project-ncl/shared-github-actions/.github/workflows/validate-gh-action.yml@9735924b878ff3890cfaf16acb28e06531963ebf # v0.0.25
